### PR TITLE
Add support for JSON Web Encryption

### PR DESCRIPTION
**Pull request by viathefalcon**
Add support for JSON Web Encryption as per https://github.com/Mastercard/client-encryption-java

### CODE REVIEW

**Comment by jaaufauvre** [comment]
@danny-gallagher @viathefalcon, waiting for https://github.com/viathefalcon/client-encryption-csharp/pull/1

**Comment by jaaufauvre** [comment]
@danny-gallagher @viathefalcon, a few improvements in https://github.com/viathefalcon/client-encryption-csharp/pull/2

**Comment by viathefalcon** [comment]
@jaaufauvre @danny-gallagher all good to go

**Comment by jaaufauvre** [comment]
Thanks @viathefalcon!

**Pull request merged**
