### PR TITLE
Encoding improvement to manage German characters

### PR DESCRIPTION
**Pull request by Biggo89**
### PR checklist

- [x] An issue/feature request has been created for this PR
- [x] Pull Request title clearly describes the work in the pull request and the Pull Request description provides details about how to validate the work. Missing information here may result in a delayed response.
- [x] File the PR against the `master` branch
- [x] The code in this PR is covered by unit tests

#### Description
Changed the encoding from ASCII to UTF8 to manage the umalaut characters

### CODE REVIEW

**Comment by Biggo89** [comment]
Sorry, but privately I'm working on the integration of this lib with a Customer that use umlauts massively, so why are you closing the issue? Sorry but I'm a little bit confused.

**Comment by Biggo89** [comment]
Anyway if this lib is intended to be used only with English characters probably it should be specified in the doc

**Comment by karen-avetisyan-mc** [comment]
> Anyway if this lib is intended to be used only with English characters probably it should be specified in the doc

I have looked at the PR, replace ASCII encoding with UTF shall be fine. I need to revert the line where you specified Net8, so I can run the test pipeline

**Comment by Biggo89** [comment]
> > Anyway if this lib is intended to be used only with English characters probably it should be specified in the doc
> 
> I have looked at the PR, replace ASCII encoding with UTF shall be fine. I need to revert the line where you specified Net8, so I can run the test pipeline

Cool, Should I have to do it on my side?

**Comment by karen-avetisyan-mc** [comment]
> > > Anyway if this lib is intended to be used only with English characters probably it should be specified in the doc
> > 
> > 
> > I have looked at the PR, replace ASCII encoding with UTF shall be fine. I need to revert the line where you specified Net8, so I can run the test pipeline
> 
> Cool, Should I have to do it on my side?

Please, just revert Net8 to net5
and I can run pipeline

**Comment by Biggo89** [comment]
> > > > Anyway if this lib is intended to be used only with English characters probably it should be specified in the doc
> > > 
> > > 
> > > I have looked at the PR, replace ASCII encoding with UTF shall be fine. I need to revert the line where you specified Net8, so I can run the test pipeline
> > 
> > 
> > Cool, Should I have to do it on my side?
> 
> Please, just revert Net8 to net5 ([f4d0647](https://github.com/Mastercard/client-encryption-csharp/commit/f4d0647b6510a2aa214ac1d1f03e2897b31ec16b)) and I can run the pipeline to check

done

**Review by karen-avetisyan-mc — APPROVED** [review]
LGTM.

**Pull request merged**
